direction: minimize
gpus_per_task: 1
dataset_name: fashion_mnist
seed: 6
hp:
    layer_dims: [64, 128, 128, 784]
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: gelu
    output_act_fn: null
    batch_size: 200
    epochs: 30
    T: 20
    use_ipc: true
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 1.0], null, true]
                default: 0.8817404084814103
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.6
        w:
            name: adamw
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 5.5069228142951346e-05
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-1], null, true]
                default: 0.001899184326397372
            momentum: 0.0
