defaults:
    - data: two_moons

optim:
    num_epochs: 8
    h:
        optimizer: sgd
        T: 8

experiment:
    ##### regular
    h_dims: [512, 1024, 2048, 4096] # [32, 128] # [256, 1024] #
    h_lr: [1.e-3, 3.e-3, 1.e-2, 3.e-2, 1.e-1, 3.e-1, 1.0]
    # h_lr: [1.] # BP
    w_lr: [1.e-5, 1.e-4, 1.e-3, 1.e-2, 1.e-1] # one LR smaller for FashionMNNIST
    optimizer_w: ["sgd", "adamw"]
    momentum_w: [0.0, 0.5, 0.9, 0.95]
    activation_fn: ["leaky_relu", "hard_tanh"]
    seeds: 3 # 10 for two_moons, 10 for two_circles, 10 for mnist

model:
    definition: PC
    init_h: forward
    init_h_sd: 0.1
    constant_layer_size: False # this overwrites num_classes and resize to make all layers of equal size
    init_w: default

run:
    n_parallel: 1
    reload_data: False # whether to reload data before each trial
    jit: True
