direction: minimize
gpus_per_task: 1
dataset_name: celeba
seed: 3
hp:
    kernel_size:
        sample_type: categorical
        sample_space: [3, 4, 5, 7]
        default: 5
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: hard_tanh
    output_act_fn: null
    batch_size: 500
    epochs: 10
    optim:
        w:
            name: adamw
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 0.0008792943102687276
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 0.002139801504043278
            momentum: 0.0
