direction: minimize
gpus_per_task: 1
dataset_name: celeba
seed: 3
hp:
    kernel_size:
        sample_type: categorical
        sample_space: [3, 4, 5, 7]
        default: 7
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: hard_tanh
    output_act_fn: null
    batch_size: 500
    epochs: 10
    optim:
        w:
            name: sgd
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-2], null, true]
                default: 0.006631758992549346
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 0.006568130658889149
            momentum:
                sample_type: float
                sample_space: [[0.0, 1.0], 0.05]
                default: 0.95
