direction: minimize
gpus_per_task: 1
dataset_name: cifar10
seed: 0
hp:
    num_layers: 3
    internal_state_dim: 4
    internal_state_channels: 8
    kernel_size:
        sample_type: categorical
        sample_space: [3, 4, 5, 7]
        default: 4
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: tanh
    output_act_fn: null
    batch_size: 200
    epochs: 30
    T: 20
    use_ipc: false
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 5e-1], null, true]
                default: 0.3686335775128242
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.55
        w:
            name: sgd
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-2], null, true]
                default: 0.0009158349688429868
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 0.005516419568456441
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.45
