direction: minimize
gpus_per_task: 1
dataset_name: celeba
seed: 0
hp:
    num_layers: 3
    internal_state_dim: 25
    internal_state_channels: 8
    kernel_size: 7
    act_fn: hard_tanh
    output_act_fn: null
    batch_size: 500
    epochs: 10
    T: 20
    use_ipc: false
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 5e-1], null, true]
                default: 0.027628774133613455
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.4
        w:
            name: sgd
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-2], null, true]
                default: 4.681580263904618e-05
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 0.00019856772275000538
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.5
