direction: minimize
gpus_per_task: 0.125
dataset_name: cifar10
seed: 0
hp:
    num_layers: 3
    internal_state_dim: 4
    internal_state_channels: 8
    kernel_size:
        sample_type: categorical
        sample_space: [3, 4, 5, 7]
        default: 7
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: tanh
    output_act_fn: null
    batch_size: 200
    epochs: 30
    T: 20
    use_ipc: true
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 1.0], null, true]
                default: 0.5277898573612123
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.25
        w:
            name: adamw
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 0.0008545440815784674
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-1], null, true]
                default: 0.0005354326611521077
            momentum: 0.0
