direction: minimize
gpus_per_task: 0.125
dataset_name: mnist
seed: 0
hp:
    layer_dims: [64, 128, 128, 784]
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: hard_tanh
    output_act_fn: null
    batch_size: 200
    epochs: 30
    T: 20
    use_ipc: true
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 1.0], null, true]
                default: 0.1713068244354728
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.05
        w:
            name: adamw
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 3.049212906900055e-05
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-1], null, true]
                default: 0.04476666954718263
            momentum: 0.0
